apiVersion: batch/v1
kind: CronJob
metadata:
  name: nautilus
spec:
  schedule: "*/11 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-nautilus
              image: nginx:latest
              imagePullPolicy: IfNotPresent
              command:
                - "/bin/sh"
                - c
                - date;echo Welcome to xfusioncorp!
          restartPolicy: OnFailure

