apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: httpd:latest
        ports:
        - containerPort: 80
    