apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: "nginx_app"
      type: front-end
  template:
    metadata:
      labels:
        app: "nginx_app"
    spec:
      containers:
        - name: nginx-contaniner
          image: nginx:latest
          ports:
            - containerPort: 80
